---

apiVersion: v2
name: enterprise-traces
type: application
version: 1.0.0
appVersion: 1.1.0
kubeVersion: ^1.10.0-0
engine: gotpl
home: https://grafana.com/products/enterprise/traces/
dependencies:
  - name: tempo-distributed
    version: ^0.13.0
    repository: https://grafana.github.io/helm-charts
  - name: minio
    alias: minio
    version: 8.0.9
    repository: https://helm.min.io/
    condition: minio.enabled
