{{- if not .Values.useExternalConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: enterprise-traces-config
  labels:
    {{- include "enterprise-traces.labels" . | nindent 4 }}
data:
  config.yaml: {{ tpl .Values.config . | b64enc }}
{{- end }}
